export * from './About/About';
export * from './CreatePost/CreatePost';
export * from './Dashboard/Dashboard';
export * from './EditPost/EditPost';
export * from './Home/Home';
export * from './Login/Login';
export * from './Post/Post';
export * from './Register/Register';
export * from './Search/Search';